baseurl = "https://blog.codequizcafe.com/"
languageCode = "en-us"
title = "Blog - Code Quiz Cafe"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Blog Home"
    url = "/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/codequizcafe"

[params]
    description = "Challenge yourself to our quizzes and prepare yourself for your future"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"